GET http://localhost:8000

###

GET http://localhost:8000/transactions/c5cb8c2079e82ae401e862f1e90914c0fd215a67aad97047b69c419d46d477a1

###

GET http://localhost:8000/transactions?page=1
Content-Type: application/json

###

POST http://localhost:8000/transaction
content-type: application/json

{
}